### ISSUE TITLE
Required target framework is missing

### ISSUE THREAD

**Issue by genscape-agodfrey** [snyk/dotnet-deps-parser#33]
### Expected behaviour
to "retest now" a dotnet project in the synk UI and have a scan performed

### Actual behaviour
error is thrown:
Required target framework is missing, has been removed or replaced from the manifest.

### Steps to reproduce
import a dotnet project with a packages.config that has TargetFrameworkVersion in the format lacking periods e.g. <TargetFrameworks>net462</TargetFrameworks>

**Comment by erichusband** [comment]
Hi @genscape-agodfrey is there also a *.csproj file in this project's repository? If so, there's a good chance that this is related to an issue that we're fixing and have a feature that's currently in beta which could resolve this.

Please log a ticket, or see your Slack channel and let me know what org's you'd like to test this feature on.

**Comment by genscape-agodfrey** [comment]
@erichusband  I have tested the fix and it works for me thank you

**Comment by krishnankuppaswamy** [comment]
I'm facing same issue. Is there a fix?
